export const MAP_TILE_SIZE = 16

export enum MapKeys {
  TILESET_NAME = 'tiles',

  // LAYERS
  BACKGROUND = 'BACKGROUND',
  GROUND = 'GROUND',
  WATER = 'WATER',
  DECORATIONS = 'DECORATIONS',
  SPAWN_POINTS = 'SPAWN_POINTS',
  MESSAGES = 'MESSAGES',

  // ENTITY OBJECT TYPES
  COINS = 'COINS',

  PLAYER_SPAWN = 'PLAYER_SPAWN',
  DAIKON_SPAWN = 'DAIKON_SPAWN',
  SQUASH_SPAWN = 'SQUASH_SPAWN',
  JELLY_SPAWN = 'JELLY_SPAWN',
  SOLDIER_SPAWN = 'SOLDIER_SPAWN',
  CACTUS_SPAWN = 'CACTUS_SPAWN',
  TANK_SPAWN = 'TANK_SPAWN',
  EYE_SPAWN = 'EYE_SPAWN',
  RADISH_SPAWN = 'RADISH_SPAWN',
  FLYING_RADISH_SPAWN = 'FLYING_RADISH_SPAWN',

  // COLLISIONS
  COLLISION_PROPERTY = 'collides',
  ENEMY_LEDGE_COLLIDERS = 'ENEMY_LEDGE_COLLIDERS',
  BACKGROUND_PLATFORM_COLLIDERS = 'BACKGROUND_PLATFORM_COLLIDERS',
  MOVABLE_PLATFORMS = 'MOVEABLE_PLATFORMS',
}
