export enum ResourceKey {
  BACKGROUND_CITY = 'BACKGROUND_CITY',
  BACKGROUND_SPRING = 'BACKGROUND_SPRING',
  BACKGROUND_SUMMER = 'BACKGROUND_SUMMER',
  BACKGROUND_WINTER = 'BACKGROUND_WINTER',
  ENTITIES = 'ENTITIES',
  MAP_TILES = 'MAP_TILES,',

  PIPELINE_GRAYSCALE = 'PIPELINE_GRAYSCALE',

  LEVEL_1 = 'LEVEL_1',
  LEVEL_2 = 'LEVEL_2',
}
