export enum ResourceKey {
  BACKGROUND_SPRING = 'BACKGROUND_SPRING',
  BACKGROUND_SUMMER = 'BACKGROUND_SUMMER',
  BACKGROUND_WINTER = 'BACKGROUND_WINTER',
  BACKGROUND_CITY = 'BACKGROUND_CITY',
  LEVEL_1 = 'LEVEL_1',
  MAP_TILES = 'MAP_TILES,',
  ENTITIES = 'ENTITIES',
  KEYS = 'KEYS',
}
